repos:
- hooks:
  - id: black
    exclude: '^env/'
    exclude: '^dvc/'
    files: '.*\.py'
    language_version: python3
  repo: https://github.com/psf/black
  rev: 22.12.0
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
- hooks:
  - id: isort
    language_version: python3
  repo: https://github.com/timothycrosley/isort
  rev: 5.11.4
- hooks:
  - id: flake8
    exclude: '^env/'
    exclude: '^dvc/'
    files: '.*\.py'
    language_version: python3
  repo: https://github.com/pycqa/flake8
  rev: 6.0.0
- hooks:
    - args:
        - -i
        - "2"
      id: beautysh
      language_version: python3
  repo: https://github.com/lovesegfault/beautysh
  rev: v6.2.1
- hooks:
  - id: generate-tests
    name: "Generate tests"
    pass_filenames: false
    always_run: true
    language: system
    files: tests
    entry: ./scripts/ci/list_tests.sh > tests/tests.json && git add tests/tests.json
  repo: local
